apiVersion: v1
kind: PersistentVolume
metadata:
  name: pulsejet-cluster-pv
  labels:
    type: local
spec:
  storageClassName: {{ .Values.pvcStorageClass }}
  accessModes:
  - ReadWriteMany
  hostPath:
    path: "/opt/volume/pulsejet"
    type: DirectoryOrCreate
  capacity:
    storage: 30Gi
  persistentVolumeReclaimPolicy: Retain
