apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pvcName }}
spec:
  accessModes: {{ .Values.pvcAccessModes }}
  resources:
    requests:
      storage: 10Gi
  storageClassName: {{ .Values.pvcStorageClass }}
