apiVersion: v1
kind: Service
metadata:
  name: {{ include "pulsejet-cluster.fullname" . }}
  labels:
    {{- include "pulsejet-cluster.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
    - port: {{ .Values.service.grpcPort }}
      targetPort: {{ .Values.service.grpcPort }}
      protocol: TCP
      name: grpc
    - port: {{ .Values.service.clusterPort }}
      targetPort: {{ .Values.service.clusterPort }}
      protocol: TCP
      name: cluster
    - port: {{ .Values.service.dashboardPort }}
      targetPort: {{ .Values.service.dashboardPort }}
      protocol: TCP
      name: dash
  selector:
    {{- include "pulsejet-cluster.selectorLabels" . | nindent 4 }}
